package com.metronearby.domain

/** Generated offline search keys; regenerate with tools/search-index/generate.py.
 * Search transliteration only, not official English station names.
 */
internal object StationPinyin {
    private val entries by lazy {
        data.trimIndent().lineSequence().associate {
            val (name, syllables) = it.split("=", limit = 2)
            name to syllables.split(" ")
        }
    }
    fun keys(name: String): List<String> {
        val syllables = entries[name] ?: return emptyList()
        return listOf(syllables.joinToString(""), syllables.joinToString("") { it.take(1) })
    }
    private val data = """
2号航站楼=2 hao hang zhan lou
2号航站楼站=2 hao hang zhan lou zhan
3号航站楼=3 hao hang zhan lou
3号航站楼站=3 hao hang zhan lou zhan
七里庄=qi li zhuang
七里庄站=qi li zhuang zhan
万安=wan an
万安站=wan an zhan
万寿寺=wan shou si
万寿寺站=wan shou si zhan
万寿路=wan shou lu
万寿路站=wan shou lu zhan
万泉河桥=wan quan he qiao
万泉河桥站=wan quan he qiao zhan
万源街=wan yuan jie
万源街站=wan yuan jie zhan
万盛东=wan sheng dong
万盛东站=wan sheng dong zhan
万盛西=wan sheng xi
万盛西站=wan sheng xi zhan
三元桥=san yuan qiao
三元桥站=san yuan qiao zhan
上地=shang di
上地站=shang di zhan
上地软件园=shang di ruan jian yuan
上地软件园站=shang di ruan jian yuan zhan
上岸=shang an
上岸站=shang an zhan
东北旺=dong bei wang
东北旺站=dong bei wang zhan
东单=dong dan
东单站=dong dan zhan
东四=dong si
东四十条=dong si shi tiao
东四十条站=dong si shi tiao zhan
东四站=dong si zhan
东坝=dong ba
东坝北=dong ba bei
东坝北站=dong ba bei zhan
东坝南=dong ba nan
东坝南站=dong ba nan zhan
东坝站=dong ba zhan
东坝西=dong ba xi
东坝西站=dong ba xi zhan
东夏园=dong xia yuan
东夏园站=dong xia yuan zhan
东大桥=dong da qiao
东大桥站=dong da qiao zhan
东湖渠=dong hu qu
东湖渠站=dong hu qu zhan
东直门=dong zhi men
东直门站=dong zhi men zhan
东管头=dong guan tou
东管头南=dong guan tou nan
东管头南站=dong guan tou nan zhan
东管头站=dong guan tou zhan
东风北桥=dong feng bei qiao
东风北桥站=dong feng bei qiao zhan
东高地=dong gao di
东高地站=dong gao di zhan
中关村=zhong guan cun
中关村站=zhong guan cun zhan
中国美术馆=zhong guo mei shu guan
中国美术馆站=zhong guo mei shu guan zhan
丰台东大街=feng tai dong da jie
丰台东大街站=feng tai dong da jie zhan
丰台南路=feng tai nan lu
丰台南路站=feng tai nan lu zhan
丰台科技园=feng tai ke ji yuan
丰台科技园站=feng tai ke ji yuan zhan
丰台站=feng tai zhan
临河里=lin he li
临河里站=lin he li zhan
丽泽商务区=li ze shang wu qu
丽泽商务区站=li ze shang wu qu zhan
义和庄=yi he zhuang
义和庄站=yi he zhuang zhan
九号村=jiu hao cun
九号村站=jiu hao cun zhan
九棵树=jiu ke shu
九棵树站=jiu ke shu zhan
九龙山=jiu long shan
九龙山站=jiu long shan zhan
二里沟=er li gou
二里沟站=er li gou zhan
五棵松=wu ke song
五棵松站=wu ke song zhan
五福堂=wu fu tang
五福堂站=wu fu tang zhan
五道口=wu dao kou
五道口站=wu dao kou zhan
亦创会展中心=yi chuang hui zhan zhong xin
亦创会展中心站=yi chuang hui zhan zhong xin zhan
亦庄同仁=yi zhuang tong ren
亦庄同仁站=yi zhuang tong ren zhan
亦庄文化园=yi zhuang wen hua yuan
亦庄文化园站=yi zhuang wen hua yuan zhan
亦庄桥=yi zhuang qiao
亦庄桥站=yi zhuang qiao zhan
亦庄火车站=yi zhuang huo che zhan
亮马桥=liang ma qiao
亮马桥站=liang ma qiao zhan
人民大学=ren min da xue
人民大学站=ren min da xue zhan
什刹海=shi cha hai
什刹海站=shi cha hai zhan
传媒大学=chuan mei da xue
传媒大学站=chuan mei da xue zhan
俸伯=feng bo
俸伯站=feng bo zhan
健德门=jian de men
健德门站=jian de men zhan
光熙门=guang xi men
光熙门站=guang xi men zhan
八宝山=ba bao shan
八宝山站=ba bao shan zhan
八角游乐园=ba jiao you le yuan
八角游乐园站=ba jiao you le yuan zhan
八角站=ba jiao zhan
八里桥=ba li qiao
八里桥站=ba li qiao zhan
公主坟=gong zhu fen
公主坟站=gong zhu fen zhan
公益西桥=gong yi xi qiao
公益西桥站=gong yi xi qiao zhan
六道口=liu dao kou
六道口站=liu dao kou zhan
六里桥=liu li qiao
六里桥东=liu li qiao dong
六里桥东站=liu li qiao dong zhan
六里桥站=liu li qiao zhan
关庄=guan zhuang
关庄站=guan zhuang zhan
军事博物馆=jun shi bo wu guan
军事博物馆站=jun shi bo wu guan zhan
军博=jun bo
军博站=jun bo zhan
农业展览馆=nong ye zhan lan guan
农业展览馆站=nong ye zhan lan guan zhan
农大南路=nong da nan lu
农大南路站=nong da nan lu zhan
分钟寺=fen zhong si
分钟寺站=fen zhong si zhan
刘家窑=liu jia yao
刘家窑站=liu jia yao zhan
前门=qian men
前门站=qian men zhan
动物园=dong wu yuan
动物园站=dong wu yuan zhan
劲松=jing song
劲松站=jing song zhan
化工=hua gong
化工站=hua gong zhan
北京南站=bei jing nan zhan
北京大学东门=bei jing da xue dong men
北京大学东门站=bei jing da xue dong men zhan
北京站=bei jing zhan
北京西站=bei jing xi zhan
北土城=bei tu cheng
北土城站=bei tu cheng zhan
北太平庄=bei tai ping zhuang
北太平庄站=bei tai ping zhuang zhan
北安河=bei an he
北安河站=bei an he zhan
北宫门=bei gong men
北宫门站=bei gong men zhan
北工大西门=bei gong da xi men
北工大西门站=bei gong da xi men zhan
北新桥=bei xin qiao
北新桥站=bei xin qiao zhan
北沙滩=bei sha tan
北沙滩站=bei sha tan zhan
北海北=bei hai bei
北海北站=bei hai bei zhan
北神树=bei shen shu
北神树站=bei shen shu zhan
北苑=bei yuan
北苑站=bei yuan zhan
北苑路北=bei yuan lu bei
北苑路北站=bei yuan lu bei zhan
北辛安=bei xin an
北辛安站=bei xin an zhan
北运河东=bei yun he dong
北运河东站=bei yun he dong zhan
北运河西=bei yun he xi
北运河西站=bei yun he xi zhan
北邵洼=bei shao wa
北邵洼站=bei shao wa zhan
十三陵景区=shi san ling jing qu
十三陵景区站=shi san ling jing qu zhan
十八里店=shi ba li dian
十八里店站=shi ba li dian zhan
十里堡=shi li pu
十里堡站=shi li pu zhan
十里河=shi li he
十里河站=shi li he zhan
南楼梓庄=nan lou zi zhuang
南楼梓庄站=nan lou zi zhuang zhan
南法信=nan fa xin
南法信站=nan fa xin zhan
南礼士路=nan li shi lu
南礼士路站=nan li shi lu zhan
南邵=nan shao
南邵站=nan shao zhan
南锣鼓巷=nan luo gu xiang
南锣鼓巷站=nan luo gu xiang zhan
双井=shuang jing
双井站=shuang jing zhan
双合=shuang he
双合站=shuang he zhan
双桥=shuang qiao
双桥站=shuang qiao zhan
古城=gu cheng
古城站=gu cheng zhan
同济南路=tong ji nan lu
同济南路站=tong ji nan lu zhan
后沙峪=hou sha yu
后沙峪站=hou sha yu zhan
周家庄=zhou jia zhuang
周家庄站=zhou jia zhuang zhan
呼家楼=hu jia lou
呼家楼站=hu jia lou zhan
和义=he yi
和义站=he yi zhan
和平西桥=he ping xi qiao
和平西桥站=he ping xi qiao zhan
和平里北街=he ping li bei jie
和平里北街站=he ping li bei jie zhan
和平门=he ping men
和平门站=he ping men zhan
善各庄=shan ge zhuang
善各庄站=shan ge zhuang zhan
嘉会湖=jia hui hu
嘉会湖站=jia hui hu zhan
四季青桥=si ji qing qiao
四季青桥站=si ji qing qiao zhan
四惠=si hui
四惠东=si hui dong
四惠东站=si hui dong zhan
四惠站=si hui zhan
四海庄=si hai zhuang
四海庄站=si hai zhuang zhan
四道桥=si dao qiao
四道桥站=si dao qiao zhan
回龙观=hui long guan
回龙观东大街=hui long guan dong da jie
回龙观东大街站=hui long guan dong da jie zhan
回龙观站=hui long guan zhan
回龙观西大街=hui long guan xi da jie
回龙观西大街站=hui long guan xi da jie zhan
团结湖=tuan jie hu
团结湖站=tuan jie hu zhan
园博园=yuan bo yuan
园博园站=yuan bo yuan zhan
国家图书馆=guo jia tu shu guan
国家图书馆站=guo jia tu shu guan zhan
国家植物园=guo jia zhi wu yuan
国家植物园站=guo jia zhi wu yuan zhan
国展=guo zhan
国展站=guo zhan zhan
国贸=guo mao
国贸站=guo mao zhan
圆明园=yuan ming yuan
圆明园站=yuan ming yuan zhan
土桥=tu qiao
土桥站=tu qiao zhan
垡头=fa tou
垡头站=fa tou zhan
复兴门=fu xing men
复兴门站=fu xing men zhan
大井=da jing
大井站=da jing zhan
大兴新城=da xing xin cheng
大兴新城站=da xing xin cheng zhan
大兴机场=da xing ji chang
大兴机场站=da xing ji chang zhan
大屯路东=da tun lu dong
大屯路东站=da tun lu dong zhan
大望路=da wang lu
大望路站=da wang lu zhan
大瓦窑=da wa yao
大瓦窑站=da wa yao zhan
大石河东=da shi he dong
大石河东站=da shi he dong zhan
大红门=da hong men
大红门南=da hong men nan
大红门南站=da hong men nan zhan
大红门站=da hong men zhan
大葆台=da bao tai
大葆台站=da bao tai zhan
大郊亭=da jiao ting
大郊亭站=da jiao ting zhan
大钟寺=da zhong si
大钟寺站=da zhong si zhan
天坛东门=tian tan dong men
天坛东门站=tian tan dong men zhan
天安门东=tian an men dong
天安门东站=tian an men dong zhan
天安门西=tian an men xi
天安门西站=tian an men xi zhan
天宫院=tian gong yuan
天宫院站=tian gong yuan zhan
天桥=tian qiao
天桥站=tian qiao zhan
天通苑=tian tong yuan
天通苑东=tian tong yuan dong
天通苑东站=tian tong yuan dong zhan
天通苑北=tian tong yuan bei
天通苑北站=tian tong yuan bei zhan
天通苑南=tian tong yuan nan
天通苑南站=tian tong yuan nan zhan
天通苑站=tian tong yuan zhan
太和桥北=tai he qiao bei
太和桥北站=tai he qiao bei zhan
太平庄=tai ping zhuang
太平庄站=tai ping zhuang zhan
太平桥=tai ping qiao
太平桥站=tai ping qiao zhan
太阳宫=tai yang gong
太阳宫站=tai yang gong zhan
奥体中心=ao ti zhong xin
奥体中心站=ao ti zhong xin zhan
奥林匹克公园=ao lin pi ke gong yuan
奥林匹克公园站=ao lin pi ke gong yuan zhan
姚家园=yao jia yuan
姚家园站=yao jia yuan zhan
孙河=sun he
孙河站=sun he zhan
学知园=xue zhi yuan
学知园站=xue zhi yuan zhan
学院桥=xue yuan qiao
学院桥站=xue yuan qiao zhan
安华桥=an hua qiao
安华桥站=an hua qiao zhan
安定门=an ding men
安定门站=an ding men zhan
安德里北街=an de li bei jie
安德里北街站=an de li bei jie zhan
安河桥北=an he qiao bei
安河桥北站=an he qiao bei zhan
安立路=an li lu
安立路站=an li lu zhan
安贞桥=an zhen qiao
安贞桥站=an zhen qiao zhan
安贞门=an zhen men
安贞门站=an zhen men zhan
宋家庄=song jia zhuang
宋家庄站=song jia zhuang zhan
定海园=ding hai yuan
定海园站=ding hai yuan zhan
定海园西=ding hai yuan xi
定海园西站=ding hai yuan xi zhan
宛平城=wan ping cheng
宛平城站=wan ping cheng zhan
宣武门=xuan wu men
宣武门站=xuan wu men zhan
富丰桥=fu feng qiao
富丰桥站=fu feng qiao zhan
将台=jiang tai
将台站=jiang tai zhan
将台西=jiang tai xi
将台西站=jiang tai xi zhan
小园=xiao yuan
小园站=xiao yuan zhan
小红门=xiao hong men
小红门站=xiao hong men zhan
屈庄=qu zhuang
屈庄站=qu zhuang zhan
屯佃=tun dian
屯佃站=tun dian zhan
崇文门=chong wen men
崇文门站=chong wen men zhan
崔各庄=cui ge zhuang
崔各庄站=cui ge zhuang zhan
工人体育场=gong ren ti yu chang
工人体育场站=gong ren ti yu chang zhan
左家庄=zuo jia zhuang
左家庄站=zuo jia zhuang zhan
巩华城=gong hua cheng
巩华城站=gong hua cheng zhan
巴沟=ba gou
巴沟站=ba gou zhan
常营=chang ying
常营站=chang ying zhan
平乐园=ping le yuan
平乐园站=ping le yuan zhan
平安里=ping an li
平安里站=ping an li zhan
平西府=ping xi fu
平西府站=ping xi fu zhan
广安门内=guang an men nei
广安门内站=guang an men nei zhan
广播学院站=guang bo xue yuan zhan
广渠门内=guang qu men nei
广渠门内站=guang qu men nei zhan
广渠门外=guang qu men wai
广渠门外站=guang qu men wai zhan
广阳城=guang yang cheng
广阳城站=guang yang cheng zhan
廖公庄=liao gong zhuang
廖公庄站=liao gong zhuang zhan
建国门=jian guo men
建国门站=jian guo men zhan
张自忠路=zhang zi zhong lu
张自忠路站=zhang zi zhong lu zhan
张郭庄=zhang guo zhuang
张郭庄站=zhang guo zhuang zhan
德茂=de mao
德茂站=de mao zhan
惠新西街北口=hui xin xi jie bei kou
惠新西街北口站=hui xin xi jie bei kou zhan
惠新西街南口=hui xin xi jie nan kou
惠新西街南口站=hui xin xi jie nan kou zhan
慈寿寺=ci shou si
慈寿寺站=ci shou si zhan
成寿寺=cheng shou si
成寿寺站=cheng shou si zhan
房山城关=fang shan cheng guan
房山城关站=fang shan cheng guan zhan
文华路=wen hua lu
文华路站=wen hua lu zhan
新发地=xin fa di
新发地站=xin fa di zhan
新宫=xin gong
新宫站=xin gong zhan
新街口=xin jie kou
新街口站=xin jie kou zhan
新首钢=xin shou gang
新首钢站=xin shou gang zhan
方庄=fang zhuang
方庄站=fang zhuang zhan
旧宫=jiu gong
旧宫站=jiu gong zhan
昌平=chang ping
昌平东关=chang ping dong guan
昌平东关站=chang ping dong guan zhan
昌平站=chang ping zhan
昌平西山口=chang ping xi shan kou
昌平西山口站=chang ping xi shan kou zhan
星城=xing cheng
星城站=xing cheng zhan
景泰=jing tai
景泰站=jing tai zhan
景风门=jing feng men
景风门站=jing feng men zhan
望京=wang jing
望京东=wang jing dong
望京东站=wang jing dong zhan
望京南=wang jing nan
望京南站=wang jing nan zhan
望京站=wang jing zhan
望京西=wang jing xi
望京西站=wang jing xi zhan
朝阳公园=zhao yang gong yuan
朝阳公园站=zhao yang gong yuan zhan
朝阳站=zhao yang zhan
朝阳门=zhao yang men
朝阳门站=zhao yang men zhan
木樨园=mu xi yuan
木樨园站=mu xi yuan zhan
木樨地=mu xi di
木樨地站=mu xi di zhan
未来科学城=wei lai ke xue cheng
未来科学城北=wei lai ke xue cheng bei
未来科学城北站=wei lai ke xue cheng bei zhan
未来科学城站=wei lai ke xue cheng zhan
朱房北=zhu fang bei
朱房北站=zhu fang bei zhan
朱辛庄=zhu xin zhuang
朱辛庄站=zhu xin zhuang zhan
来广营=lai guang ying
来广营站=lai guang ying zhan
杨庄=yang zhuang
杨庄站=yang zhuang zhan
林萃桥=lin cui qiao
林萃桥站=lin cui qiao zhan
果园=guo yuan
果园站=guo yuan zhan
枣园=zao yuan
枣园站=zao yuan zhan
枣营=zao ying
枣营站=zao ying zhan
柳芳=liu fang
柳芳站=liu fang zhan
栗园庄=li yuan zhuang
栗园庄站=li yuan zhuang zhan
桥户营=qiao hu ying
桥户营站=qiao hu ying zhan
桥湾=qiao wan
桥湾站=qiao wan zhan
梨园=li yuan
梨园站=li yuan zhan
森林公园南门=sen lin gong yuan nan men
森林公园南门站=sen lin gong yuan nan men zhan
榆树庄=yu shu zhuang
榆树庄站=yu shu zhuang zhan
模式口=mo shi kou
模式口站=mo shi kou zhan
次渠=ci qu
次渠北=ci qu bei
次渠北站=ci qu bei zhan
次渠南=ci qu nan
次渠南站=ci qu nan zhan
次渠站=ci qu zhan
欢乐谷景区=huan le gu jing qu
欢乐谷景区站=huan le gu jing qu zhan
永丰=yong feng
永丰南=yong feng nan
永丰南站=yong feng nan zhan
永丰站=yong feng zhan
永安里=yong an li
永安里站=yong an li zhan
永定门外=yong ding men wai
永定门外站=yong ding men wai zhan
永泰庄=yong tai zhuang
永泰庄站=yong tai zhuang zhan
沙河=sha he
沙河站=sha he zhan
沙河高教园=sha he gao jiao yuan
沙河高教园站=sha he gao jiao yuan zhan
泥洼=ni wa
泥洼站=ni wa zhan
泰河路=tai he lu
泰河路站=tai he lu zhan
洪泰庄=hong tai zhuang
洪泰庄站=hong tai zhuang zhan
海户屯=hai hu tun
海户屯站=hai hu tun zhan
海淀五路居=hai dian wu lu ju
海淀五路居站=hai dian wu lu ju zhan
海淀黄庄=hai dian huang zhuang
海淀黄庄站=hai dian huang zhuang zhan
清华东路西口=qing hua dong lu xi kou
清华东路西口站=qing hua dong lu xi kou zhan
清河小营桥=qing he xiao ying qiao
清河小营桥站=qing he xiao ying qiao zhan
清河站=qing he zhan
清河营=qing he ying
清河营站=qing he ying zhan
清源路=qing yuan lu
清源路站=qing yuan lu zhan
温阳路=wen yang lu
温阳路站=wen yang lu zhan
湾子=wan zi
湾子站=wan zi zhan
潘家园=pan jia yuan
潘家园站=pan jia yuan zhan
潘家园西=pan jia yuan xi
潘家园西站=pan jia yuan xi zhan
潞城=lu cheng
潞城站=lu cheng zhan
潞阳=lu yang
潞阳站=lu yang zhan
瀛海=ying hai
瀛海站=ying hai zhan
火器营=huo qi ying
火器营站=huo qi ying zhan
火箭万源=huo jian wan yuan
火箭万源站=huo jian wan yuan zhan
灯市口=deng shi kou
灯市口站=deng shi kou zhan
灵境胡同=ling jing hu tong
灵境胡同站=ling jing hu tong zhan
焦化厂=jiao hua chang
焦化厂站=jiao hua chang zhan
燕山=yan shan
燕山站=yan shan zhan
牛街=niu jie
牛街站=niu jie zhan
牡丹园=mu dan yuan
牡丹园站=mu dan yuan zhan
物资学院路=wu zi xue yuan lu
物资学院路站=wu zi xue yuan lu zhan
玉泉路=yu quan lu
玉泉路站=yu quan lu zhan
玉渊潭东门=yu yuan tan dong men
玉渊潭东门站=yu yuan tan dong men zhan
王府井=wang fu jing
王府井站=wang fu jing zhan
环球度假区=huan qiu du jia qu
环球度假区站=huan qiu du jia qu zhan
环球影城站=huan qiu ying cheng zhan
珠市口=zhu shi kou
珠市口站=zhu shi kou zhan
瑞合庄=rui he zhuang
瑞合庄站=rui he zhuang zhan
甘家口=gan jia kou
甘家口站=gan jia kou zhan
生命科学园=sheng ming ke xue yuan
生命科学园站=sheng ming ke xue yuan zhan
生物医药基地=sheng wu yi yao ji di
生物医药基地站=sheng wu yi yao ji di zhan
田村=tian cun
田村站=tian cun zhan
白堆子=bai dui zi
白堆子站=bai dui zi zhan
白盆窑=bai pen yao
白盆窑站=bai pen yao zhan
白石桥南=bai shi qiao nan
白石桥南站=bai shi qiao nan zhan
百子湾=bai zi wan
百子湾站=bai zi wan zhan
看丹=kan dan
看丹站=kan dan zhan
知春路=zhi chun lu
知春路站=zhi chun lu zhan
知春里=zhi chun li
知春里站=zhi chun li zhan
石佛营=shi fu ying
石佛营站=shi fu ying zhan
石厂=shi chang
石厂站=shi chang zhan
石榴庄=shi liu zhuang
石榴庄站=shi liu zhuang zhan
石门=shi men
石门站=shi men zhan
磁器口=ci qi kou
磁器口站=ci qi kou zhan
科怡路=ke yi lu
科怡路站=ke yi lu zhan
积水潭=ji shui tan
积水潭站=ji shui tan zhan
稻田=dao tian
稻田站=dao tian zhan
稻香湖路=dao xiang hu lu
稻香湖路站=dao xiang hu lu zhan
立水桥=li shui qiao
立水桥南=li shui qiao nan
立水桥南站=li shui qiao nan zhan
立水桥站=li shui qiao zhan
管庄=guan zhuang
管庄站=guan zhuang zhan
篱笆房=li ba fang
篱笆房站=li ba fang zhan
紫草坞=zi cao wu
紫草坞站=zi cao wu zhan
红军营=hong jun ying
红军营站=hong jun ying zhan
红庙=hong miao
红庙站=hong miao zhan
红莲南路=hong lian nan lu
红莲南路站=hong lian nan lu zhan
纪家庙=ji jia miao
纪家庙站=ji jia miao zhan
经海一路=jing hai yi lu
经海一路站=jing hai yi lu zhan
经海路=jing hai lu
经海路站=jing hai lu zhan
群芳=qun fang
群芳站=qun fang zhan
肖村=xiao cun
肖村站=xiao cun zhan
育新=yu xin
育新站=yu xin zhan
育知路=yu zhi lu
育知路站=yu zhi lu zhan
良乡南关=liang xiang nan guan
良乡南关站=liang xiang nan guan zhan
良乡大学城=liang xiang da xue cheng
良乡大学城北=liang xiang da xue cheng bei
良乡大学城北站=liang xiang da xue cheng bei zhan
良乡大学城站=liang xiang da xue cheng zhan
良乡大学城西=liang xiang da xue cheng xi
良乡大学城西站=liang xiang da xue cheng xi zhan
芍药居=shao yao ju
芍药居站=shao yao ju zhan
花乡东桥=hua xiang dong qiao
花乡东桥站=hua xiang dong qiao zhan
花园桥=hua yuan qiao
花园桥站=hua yuan qiao zhan
花庄=hua zhuang
花庄站=hua zhuang zhan
花梨坎=hua li kan
花梨坎站=hua li kan zhan
苏州桥=su zhou qiao
苏州桥站=su zhou qiao zhan
苏州街=su zhou jie
苏州街站=su zhou jie zhan
苏庄=su zhuang
苏庄站=su zhuang zhan
苹果园=ping guo yuan
苹果园站=ping guo yuan zhan
茶棚=cha peng
茶棚站=cha peng zhan
草房=cao fang
草房站=cao fang zhan
草桥=cao qiao
草桥站=cao qiao zhan
荣京东街=rong jing dong jie
荣京东街站=rong jing dong jie zhan
荣昌东街=rong chang dong jie
荣昌东街站=rong chang dong jie zhan
莲花桥=lian hua qiao
莲花桥站=lian hua qiao zhan
菜市口=cai shi kou
菜市口站=cai shi kou zhan
菜户营=cai hu ying
菜户营站=cai hu ying zhan
蒲黄榆=pu huang yu
蒲黄榆站=pu huang yu zhan
蓝靛厂=lan dian chang
蓝靛厂站=lan dian chang zhan
蓟门桥=ji men qiao
蓟门桥站=ji men qiao zhan
虎坊桥=hu fang qiao
虎坊桥站=hu fang qiao zhan
融兴街=rong xing jie
融兴街站=rong xing jie zhan
褡裢坡=da lian po
褡裢坡站=da lian po zhan
西二旗=xi er qi
西二旗站=xi er qi zhan
西北旺=xi bei wang
西北旺站=xi bei wang zhan
西单=xi dan
西单站=xi dan zhan
西四=xi si
西四站=xi si zhan
西土城=xi tu cheng
西土城站=xi tu cheng zhan
西坝河=xi ba he
西坝河站=xi ba he zhan
西小口=xi xiao kou
西小口站=xi xiao kou zhan
西局=xi ju
西局站=xi ju zhan
西直门=xi zhi men
西直门站=xi zhi men zhan
西红门=xi hong men
西红门站=xi hong men zhan
西苑=xi yuan
西苑站=xi yuan zhan
西钓鱼台=xi diao yu tai
西钓鱼台站=xi diao yu tai zhan
西铁营=xi tie ying
西铁营站=xi tie ying zhan
西黄村=xi huang cun
西黄村站=xi huang cun zhan
角门东=jiao men dong
角门东站=jiao men dong zhan
角门西=jiao men xi
角门西站=jiao men xi zhan
车公庄=che gong zhuang
车公庄站=che gong zhuang zhan
车公庄西=che gong zhuang xi
车公庄西站=che gong zhuang xi zhan
车道沟=che dao gou
车道沟站=che dao gou zhan
达官营=da guan ying
达官营站=da guan ying zhan
通州北关=tong zhou bei guan
通州北关站=tong zhou bei guan zhan
通州北苑=tong zhou bei yuan
通州北苑站=tong zhou bei yuan zhan
通运门=tong yun men
通运门站=tong yun men zhan
郎辛庄=lang xin zhuang
郎辛庄站=lang xin zhuang zhan
郝家府=hao jia fu
郝家府站=hao jia fu zhan
郭公庄=guo gong zhuang
郭公庄站=guo gong zhuang zhan
郭庄子=guo zhuang zi
郭庄子站=guo zhuang zi zhan
金台夕照=jin tai xi zhao
金台夕照站=jin tai xi zhao zhan
金台路=jin tai lu
金台路站=jin tai lu zhan
金安桥=jin an qiao
金安桥站=jin an qiao zhan
金鱼胡同=jin yu hu tong
金鱼胡同站=jin yu hu tong zhan
长春桥=chang chun qiao
长春桥站=chang chun qiao zhan
长椿街=chang chun jie
长椿街站=chang chun jie zhan
长阳=chang yang
长阳站=chang yang zhan
阎村=yan cun
阎村东=yan cun dong
阎村东站=yan cun dong zhan
阎村站=yan cun zhan
阜成门=fu cheng men
阜成门站=fu cheng men zhan
阜通=fu tong
阜通站=fu tong zhan
陶然亭=tao ran ting
陶然亭站=tao ran ting zhan
雍和宫=yong he gong
雍和宫站=yong he gong zhan
霍营=huo ying
霍营东=huo ying dong
霍营东站=huo ying dong zhan
霍营站=huo ying zhan
青年路=qing nian lu
青年路站=qing nian lu zhan
顺义=shun yi
顺义站=shun yi zhan
颐和园西门=yi he yuan xi men
颐和园西门站=yi he yuan xi men zhan
饶乐府=rao yue fu
饶乐府站=rao yue fu zhan
首经贸=shou jing mao
首经贸站=shou jing mao zhan
香山=xiang shan
香山站=xiang shan zhan
马各庄=ma ge zhuang
马各庄站=ma ge zhuang zhan
马家堡=ma jia pu
马家堡站=ma jia pu zhan
马泉营=ma quan ying
马泉营站=ma quan ying zhan
马甸桥=ma dian qiao
马甸桥站=ma dian qiao zhan
马连洼=ma lian wa
马连洼站=ma lian wa zhan
驼房营=tuo fang ying
驼房营站=tuo fang ying zhan
高家园=gao jia yuan
高家园站=gao jia yuan zhan
高楼金=gao lou jin
高楼金站=gao lou jin zhan
高碑店=gao bei dian
高碑店站=gao bei dian zhan
高米店北=gao mi dian bei
高米店北站=gao mi dian bei zhan
高米店南=gao mi dian nan
高米店南站=gao mi dian nan zhan
魏公村=wei gong cun
魏公村站=wei gong cun zhan
鹿圈东=lu quan dong
鹿圈东站=lu quan dong zhan
黄厂=huang chang
黄厂站=huang chang zhan
黄村火车站=huang cun huo che zhan
黄村西大街=huang cun xi da jie
黄村西大街站=huang cun xi da jie zhan
黄渠=huang qu
黄渠站=huang qu zhan
黑庄户=hei zhuang hu
黑庄户站=hei zhuang hu zhan
鼓楼大街=gu lou da jie
鼓楼大街站=gu lou da jie zhan
龙泽=long ze
龙泽站=long ze zhan
龙泽西=long ze xi
龙泽西站=long ze xi zhan
    """
}
